name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # This permission is needed for gh-pages to push to the gh-pages branch
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build only client
        run: npm run build:client
        
      - name: List build directory
        run: |
          echo "Build directory contents:"
          ls -la dist/public/
          
      - name: Create 404.html (SPA fallback)
        run: |
          cp dist/public/index.html dist/public/404.html
        
      - name: Deploy with gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'